org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# v89: disabilita configuration-cache (causa bug "Cannot mutate dependencies"
# con AGP 8.x + Gradle 9.x + viewBinding)
org.gradle.configuration-cache=false
org.gradle.unsafe.configuration-cache=false
